In [5]:
import numpy as np #ini cuma agar lebih pendek aja 

# 1D array
a = np.array([1,2,3,4,5])
print ("a : ",a)

#2D array ->itu tuh kayak matrix pada umumnya aja 
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("b : \n", b)

# Spesial Array

# 1. Zeros -> ini tuh kita bisa mendeclare sebuah array yang isinya full 0, declare : np.zeros ((a,b)). a : baris, b : kolom
zeros = np.zeros ((2,3)) 

#2. Ones -> mendeclare sebuah array yang isi dari valuenya adalah one/1. declare : np.ones ((a,b)) , a :baris, b : kolom 
ones = np.ones ((2,2))

# 3. arange -> (start, stop,step)
range_array = np.arange(0, 10, 2)  # 0,2,4,6,8

# 4. lispace -> (start ,stop , jumlah)
linspace_array = np.linspace(0, 1, 5)  # 0, 0.25, 0.5, 0.75, 1

print("zeros:\n", zeros)
print("ones:\n", ones)
print("arange:", range_array)
print("linspace:", linspace_array)

a :  [1 2 3 4 5]
b : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
